/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_A4123A30__
#define __PLUGINEDITOR_H_A4123A30__

#include <vector>
#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "ChannelView.h"

//==============================================================================
/**
*/
class QdvstAudioProcessorEditor  :	public AudioProcessorEditor,
									public SliderListener,
									public juce::ComboBox::Listener								
{
public:
    QdvstAudioProcessorEditor (QdvstAudioProcessor* ownerFilter);
    ~QdvstAudioProcessorEditor();

    void paint (Graphics& g);
	void sliderValueChanged(Slider* slider);
	void comboBoxChanged (ComboBox* comboBoxThatHasChanged);

	juce::Slider* testknob;
	juce::Label* channelLabel;
	juce::ComboBox* channelSelector;

private:
	std::vector<ChannelView*> channels;
	int channelAmount;	// amount of channels active in the pluginprocessor
};


#endif  // __PLUGINEDITOR_H_A4123A30__
