/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#ifndef __PLUGINEDITOR_H_A4123A30__
#define __PLUGINEDITOR_H_A4123A30__

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"


//==============================================================================
/**
*/
class QdvstAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    QdvstAudioProcessorEditor (QdvstAudioProcessor* ownerFilter);
    ~QdvstAudioProcessorEditor();

    //==============================================================================
    // This is just a standard Juce paint method...
    void paint (Graphics& g);
};


#endif  // __PLUGINEDITOR_H_A4123A30__
