/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic startup code for a Juce application.

  ==============================================================================
*/

#include <cstdio>
#include <Windows.h>
#include "PluginProcessor.h"
#include "PluginEditor.h"

void initConsole(void) {
    AllocConsole();
    freopen( "CON", "w", stdout );
    freopen( "CON", "w", stderr );
}

//==============================================================================
QdvstAudioProcessorEditor::QdvstAudioProcessorEditor (QdvstAudioProcessor* ownerFilter)
    : AudioProcessorEditor (ownerFilter)
{
	
	#ifdef DEBUG
	initConsole();
	printf("Starting GUI.\n");
	#endif

    setSize (640, 480);
}

QdvstAudioProcessorEditor::~QdvstAudioProcessorEditor()
{
	#ifdef DEBUG
	FreeConsole();
	#endif
}

//==============================================================================
void QdvstAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);
    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("PEISIK ADDQD VST",
                      0, 0, getWidth(), getHeight(),
                      Justification::topLeft, 1);
}
